background #1a1b26
foreground #c0caf5

background_opacity 0.9

# Default font family (Must be installed)
font_family      Noto Sans Nerd Font

# Font size
font_size        12.0

# Bold font (usually same family, weight bold)
bold_font        auto
italic_font      auto
bold_italic_font auto
